name: YouDoVoodoo
favicon: null
layout_spectrum: 0.80941695952788
typography_spectrum: 0.5935651657637209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9586651180870831
  lightness: 0.8741413725074381
  saturation: 0.8321231817826629
  rhythmicContrast: 0.41462355898693204
purpose: []
